name: CI
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cabal: ["3.2"]
        ghc: ["8.10"]
    steps:
      - uses: actions/checkout@v2

      - id: tools
        uses: actions/setup-haskell@v1.1
        with:
          ghc-version: ${{ inputs.ghc-version }}
          cabal-version: ${{ inputs.cabal-version }}

      - uses: merijn/github-actions@master
        with:
          ghc-path: ${{ steps.tools.ghc-path }}
